import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-800 text-white p-4">
          <a href="/">หน้าแรก</a> | <a href="/about">เกี่ยวกับเรา</a>
        </nav>
  
        {children} {/* หน้า page.tsx ต่างๆ จะมาโผล่ตรงนี้ */}
  
        <footer className="p-4 border-t">
          © 2026 Project AIVD
        </footer>
      </body>
    </html>
  );
}
